# reference pose generation
ref_pose_input_path: "data/pose_templates/images"
ref_pose_output_path: "data/pose_templates/predictions"
ref_pose_model: "yolov8x"

# save debug images during prediction
debug_images_path: "data/debug_images"
save_debug_poses: True
save_video: False

# prediction
prediction_model: "yolov8s" # s - 50fps     m - 28fps
video_source: 0
camera_resolution: [1080, 1920]
multi: True
show_center_box: True
prediction_pose_names: [
  'arnold2.json', 'leaonardo.json', 'david.json', 'usain.json', 'muhammad.json', 'mario.json', 'discobol.json', 'freddie.json', 'superman.json', 'jordan.json',
  'bond.json', 'dab_full.json', 'haaland.json', 'legolas-orcs.json', 'max_vestappen.json', 'navratilova.json', 'patmat.json'
]

# objective
"comparison_method": "multi_angle"    # 'angle', 'multi_angle'
"after_complete": "reset"             # 'end', 'reset'
"poses_in_row": 30
"similarity_threshold": 0.85
"bot_similarity_threshold": 0.4
"similarity_smoothing": 0.9
"name_to_text_file_name": "texts.json"

# predictor
"number_of_colors": 21
"show_result_time": 5
"key_colors": [[232, 116, 97], [244, 211, 94], [98, 254, 153]]
"debug_numbers_in_image": False